export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAIELD';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCC = 'FETCH_PRODUCT_SUCC';

export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
    